name: vehicle_tracking
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
#  background_locator: ^1.6.12
  bloc: ^8.0.2
  cloud_firestore: ^5.0.2
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_map: ^7.0.1
  flutter_screenutil: ^5.5.1
  fluttertoast: ^8.0.8
  geocoding: ^3.0.0
  geolocator: ^10.0.0
  google_fonts: ^4.0.0
  intl: 
  latlong2: ^0.9.1
#  location: ^6.0.2
  shared_preferences: ^2.2.3
  splash_screen_view: ^3.0.0
  uuid: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
#  freezed: ^2.0.4
#  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/lang/
    - assets/images/
    - assets/lottie/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
fonts:
  - family: Cairo
    fonts:
      - asset: assets/fonts/Cairo-Black.ttf
        weight: 200
      - asset: assets/fonts/Cairo-Bold.ttf
        weight: 700
      - asset: assets/fonts/Cairo-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Cairo-ExtraLight.ttf
        weight: 900
      - asset: assets/fonts/Cairo-Light.ttf
        weight: 300
      - asset: assets/fonts/Cairo-Medium.ttf
        weight: 500
      - asset: assets/fonts/Cairo-Regular.ttf
        weight: 400
      - asset: assets/fonts/Cairo-SemiBold.ttf
        weight: 600
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
